### ISSUE TITLE
Your script is great, but I had some trouble getting it to run..

### ISSUE THREAD

**Issue by miggland** [jp-powers/fan-control#16]
Hi,

your script helped a lot. Some others I have tried did not work on pfSense!

I had some trouble installing, testing, changing configs - problems I fixed on the basis of your work. I made separate PRs for all of my fixes. Feel free to use what you like..

**Comment by jp-powers** [comment]
Hi @miggland !

I'm at work but took a quick peak through the changes. They look good so I'll probably accept them as is, but I won't be able to do it til I get home. 

Thanks for the changes, including one I was meaning to do for a while and never got around to!

**Comment by jp-powers** [comment]
Merged everything unchanged, thanks again for the input and effort!
