### ISSUE TITLE
Empty hard disk array results in division by 0

### ISSUE THREAD

**Issue by argasek** [jp-powers/fan-control#3]
Hi,

Thanks for wonderful script! I've run it with a decent level of success on my server via Proxmox. The only issue I have is that none of my disks there report a "194" ID using smartctl, so I don't know the temperature. I only have "Airflow_Temperature_Cel" (190). Thus, I made the array of hdd empty, but as it's length is zero, the script crashes. It would be really nice if it could ignore HDD temperatures logic alltogether. Not a Python expert, so no PR here...

**Comment by jp-powers** [comment]
Hi!

Right now I do that in the pfSense "version" of the script (who cares about a router's storage temps? (inb4 someone jumps in to STERNLY corrects me on that)), which won't quite work for you on Proxmox as easily as "switching" to pfSense in the config.

I can rework some things to make that more user configurable so it can work for Proxmox as well.

**Comment by jp-powers** [comment]
Hey argasek,

Apologies for the delay, I was working on this during some down time while working from home. I also decided to use this as an opportunity to properly setup my IDE to do git pull/merges so I can do these fixes more easily.

The latest version that's up now has the necessary changes for this. There is an extra option in the gen-config.py, `temp_focus` that you'll want to change.

Whether that works for you or not, let me know!

**Comment by argasek** [comment]
Setting the `temp_focus` worked as a charm! Many thanks for your efforts to improve the script! <3
