### ISSUE TITLE
Installation didn't succeed on proxmox VE 8.0.4

### ISSUE THREAD

**Issue by Tanguille** [jp-powers/fan-control#8]
After seemingly installing succesfully  at first sight on Proxmox VE 8.0.4, my system can't find the service, even after rebooting. System is an AMD 5800x with x470D4U motherboard. 

Output of install:
```sh
root@node000001:~/fan-control# ./install.sh
./install.sh: 4: [: Illegal number: 
What OS are you installing on?
1 = TrueNAS CORE
2 = Proxmox
3 = pfSense
My OS: 3
You Selected pfSense
If you selected incorrectly, Ctrl+C now in next 5 seconds!
creating fan-control.py
creating gen-config.py
copying fan-control.sh to /root/fan-control/
This is used to start/stop/restart the script. Alongside nohup it will survive thru shell session closure.
making appropriate files executable
stat: cannot read file system information for '%0Lp': No such file or directory
./install.sh: 29: [: File:: unexpected operator
gen-config.py did not get proper permissions, please manually run the following!
chmod 755 /root/fan-control/gen-config.py
stat: cannot read file system information for '%0Lp': No such file or directory
./install.sh: 35: [: File:: unexpected operator
fan-control.py did not get proper permissions, please manually run the following!
chmod 755 /root/fan-control/fan-control.py
Starting nano to edit the config file generator that now. Ctrl+X when complete to save and exit.
(sleeping for 10 seconds to cancel if wanted)
Executing gen-config.py to generate the config file
./install.sh: 143: /root/fan-control/gen-config.py: not found
Copying fan-control.sh to /usr/local/etc/rc.d/ so it can auto start on reboots
cp: cannot create regular file '/usr/local/etc/rc.d/': Not a directory
fan-control.py is setup. Starting the script now.
root@node000001:~/fan-control# nohup: appending output to 'nohup.out'
```

I read the readme multiple times to make sure I didn't look over something but can't figure out what I have done wrong.

**Comment by jp-powers** [comment]
Hi @Tanguille,

Thanks for providing the copy/paste, it looks to provide the answer. You said at the top you're installing on proxmox but when running install.sh you selected pfSense. The reason I ask you to select one is each OS requires different parts to function, and pfSense uses a different methodology from proxmox. Try installing it again and entering "2" when prompted for the OS. You may need to run the uninstall.sh script and select pfSense for it first to "clean up" the unintended install attempt. 

Also, it's worth noting, I have not included any impitool implementation for ASRock Rack systems. It *might* work with dell or supermicro's, but I doubt it.

**Comment by Tanguille** [comment]
Sorry for this embarrassing issue, I would have sworen I have chosen proxmox but was obviously wrong. I ran uninstall with option 3 and tried again with the right option and ran into some issues. So I can conclude this script is not suited for my machine?

This is the output of the install: 
```sh
./install.sh
./install.sh: 4: [: Illegal number: 
What OS are you installing on?
1 = TrueNAS CORE
2 = Proxmox
3 = pfSense
My OS: 2
You selected Proxmox
If you selected incorrectly, Ctrl+C now in next 5 seconds!
installing requirements via apt. If already installed apt will skip on it's own.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ipmitool is already the newest version (1.8.19-4).
lm-sensors is already the newest version (1:3.6.0-7.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
creating fan-control.py
creating gen-config.py
copying service file to /root/fan-control/
If you'd like to make changes to it/how it runs you can do that here
making appropriate files executable
gen-config.py has proper permissions
fan-control.py has proper permissions
Starting nano to edit the config file generator that now. Ctrl+X when complete to save and exit.
(sleeping for 10 seconds to cancel if wanted)
Executing gen-config.py to generate the config file
Configuration file successfully written
Creating link to service file
ln: failed to create symbolic link '/etc/systemd/system/fan-control.service': File exists
reloading daemons
enabling fan-control.service
starting fan-control
× fan-control.service - Fan Control
     Loaded: loaded (/etc/systemd/system/fan-control.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-10-23 18:32:17 CEST; 750ms ago
   Duration: 65ms
    Process: 8902 ExecStart=/root/fan-control/fan-control.py (code=exited, status=1/FAILURE)
   Main PID: 8902 (code=exited, status=1/FAILURE)
        CPU: 28ms

Oct 23 18:32:17 node000001 systemd[1]: fan-control.service: Scheduled restart job, restart counter is at 5.
Oct 23 18:32:17 node000001 systemd[1]: Stopped fan-control.service - Fan Control.
Oct 23 18:32:17 node000001 systemd[1]: fan-control.service: Start request repeated too quickly.
Oct 23 18:32:17 node000001 systemd[1]: fan-control.service: Failed with result 'exit-code'.
Oct 23 18:32:17 node000001 systemd[1]: Failed to start fan-control.service - Fan Control.
```

**Comment by jp-powers** [comment]
No worries, I figured it was a typo, those buttons are literally right next to each other ;-)

It's definitely installing properly now, but sysctl status isn't providing much helpful info as to why it's exiting early. My guess would be that it's failing to execute impitool properly since it's really unlikely ASRock Rack and Dell or Supermicro use the same impitool raw commands to control the fan speeds.

As I don't own one of their boards I can't do any testing myself to add in support for them. If you're up for it you can try to add in support yourself, it's just a matter of finding the correct ipmitool raw commands to set/control fan speeds. I could try to find some time to research what to use and add it in later, but I'm pretty busy with other things in my day to day so it could be a while. I have been thinking about getting one of their X570 boards for my second truenas box, so even if you decide to skip it for now, check back in in the future, support might be here eventually.

**Comment by Tanguille** [comment]
It is not a priority for me now but rather a nice to have so for now I just won't use it. If you want me to test something I'm willing to do so. I will look back from time to time to see how the project is going because fancontrol is something overlooked in the serverspace in my experience and this project looks like a very nice way to address it since it's so simple to install and defaults look good. So thanks for the efforts and keep up the good work :)

**Comment by jp-powers** [comment]
I'm going to go ahead and close the issue, I'm adding generic ASRock Rack ipmi raw command support to my todo list, I'll try to get it in in a future update for testing
